# Bakes Reactor7 into scripts/src/shared/Glyphs.luau: every printable ASCII character as the
# pixels the font draws at its own size.
#
#   godot --headless --path . -s res://tests/bake_glyphs.gd -- [path to Reactor7 .ttf]
#
# Pixels and not the font: no Roblox API draws a string into an EditableImage and a cape's picture
# is an image, so client and server both stamp words out of this table. Reactor7 is a pixel font on
# a 16-pixel grid -- SIZE 16 rasterises to exactly its own pixels, any other size smears. The .ttf
# defaults to the host's user://media cache of place-assets.json's "Reactor7".
extends SceneTree

const SIZE := 16
const OUT := "res://scripts/src/shared/Glyphs.luau"

func _initialize() -> void:
	var args := OS.get_cmdline_user_args()
	var path := args[0] if args.size() > 0 else OS.get_user_data_dir().path_join("media/8b042f679f1da94798dda7c887b6abba.ttf")
	var f := FontFile.new()
	if f.load_dynamic_font(path) != OK:
		printerr("could not load ", path)
		quit(1)
		return
	f.antialiasing = TextServer.FONT_ANTIALIASING_NONE
	f.hinting = TextServer.HINTING_NONE
	f.subpixel_positioning = TextServer.SUBPIXEL_POSITIONING_DISABLED
	var sz := Vector2i(SIZE, 0)
	f.render_range(0, sz, 32, 126)
	var ascent := int(f.get_cache_ascent(0, SIZE))
	var descent := int(f.get_cache_descent(0, SIZE))

	var lines := PackedStringArray()
	lines.append("-- Reactor7, as pixels: every printable ASCII character the way the font draws it at 16.")
	lines.append("--")
	lines.append("-- GENERATED by tests/bake_glyphs.gd from the place's own Reactor7. Do not edit by hand; bake it")
	lines.append("-- again. Words on a cape are stamped out of this (Glyphs.stamp), because a script cannot draw")
	lines.append("-- text into an image and the cape's picture is an image.")
	lines.append("--")
	lines.append("-- Each glyph: a = how far the pen moves, x/y = where its box sits from the pen and the")
	lines.append("-- baseline, rows = its pixels top to bottom, # for ink.")
	lines.append("local Glyphs = {}")
	lines.append("")
	lines.append("Glyphs.ASCENT = %d" % ascent)
	lines.append("Glyphs.DESCENT = %d" % descent)
	lines.append("Glyphs.LINE = %d" % (ascent + descent))
	lines.append("")
	lines.append("Glyphs.set = {")
	for code in range(32, 127):
		var gi := f.get_glyph_index(SIZE, code, 0)
		var adv := int(f.get_glyph_advance(0, SIZE, gi).x)
		var off := f.get_glyph_offset(0, sz, gi)
		var uv := f.get_glyph_uv_rect(0, sz, gi)
		var ti := f.get_glyph_texture_idx(0, sz, gi)
		var rows := PackedStringArray()
		if ti >= 0 and uv.size.x > 0:
			var img := f.get_texture_image(0, sz, ti)
			for y in int(uv.size.y):
				var row := ""
				for x in int(uv.size.x):
					row += "#" if img.get_pixel(int(uv.position.x) + x, int(uv.position.y) + y).a > 0.5 else "."
				rows.append("\"%s\"" % row)
		var ch := String.chr(code)
		var key := "\"\\\"\"" if ch == "\"" else ("\"\\\\\"" if ch == "\\" else "\"%s\"" % ch)
		lines.append("\t[%s] = { a = %d, x = %d, y = %d, rows = { %s } }," % [key, adv, int(off.x), int(off.y), ", ".join(rows)])
	lines.append("}")
	lines.append("")
	lines.append("""--- How wide and tall `text` comes out at `scale` (a whole number: each font pixel drawn that
--- many pixels square, which keeps a pixel font crisp).
function Glyphs.measure(text: string, scale: number): (number, number)
	local w = 0
	for i = 1, #text do
		local g = Glyphs.set[string.sub(text, i, i)] or Glyphs.set["?"]
		w += g.a
	end
	return w * scale, Glyphs.LINE * scale
end

--- Stamps `text` into a flat RGBA array `px` (`width` pixels across, values 0..255), its top-left
--- at x, y, in `rgba` = {r, g, b, a}. Anything off the image is dropped rather than wrapped.
function Glyphs.stamp(px, width: number, height: number, text: string, x: number, y: number, rgba, scale: number)
	scale = math.max(1, math.floor(scale or 1))
	local pen = math.floor(x)
	local baseline = math.floor(y) + Glyphs.ASCENT * scale
	for i = 1, #text do
		local g = Glyphs.set[string.sub(text, i, i)] or Glyphs.set["?"]
		for r, row in ipairs(g.rows) do
			for c = 1, #row do
				if string.byte(row, c) == 35 then            -- "#"
					local left = pen + (g.x + c - 1) * scale
					local top = baseline + (g.y + r - 1) * scale
					for dy = 0, scale - 1 do
						local py = top + dy
						if py >= 0 and py < height then
							for dx = 0, scale - 1 do
								local qx = left + dx
								if qx >= 0 and qx < width then
									local o = (py * width + qx) * 4
									px[o + 1], px[o + 2], px[o + 3], px[o + 4] = rgba[1], rgba[2], rgba[3], rgba[4] or 255
								end
							end
						end
					end
				end
			end
		end
		pen += g.a * scale
	end
end

return Glyphs""")
	var out := FileAccess.open(OUT, FileAccess.WRITE)
	out.store_string("\n".join(lines) + "\n")
	out.close()
	print("baked %d glyphs, ascent %d, descent %d -> %s" % [95, ascent, descent, OUT])
	quit(0)
